//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlfaMap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Workplace.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap connect {
            get {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg version=&quot;1.1&quot; id=&quot;{{id}}&quot; width=&quot;{{width}}&quot; height=&quot;{{height}}&quot; viewBox=&quot;0 0 {{width}} {{height}}&quot;&gt;
        ///    &lt;g id=&quot;levels&quot;&gt;
        ///        &lt;g id=&quot;{{id}}&quot;&gt;
        ///            &lt;g id=&quot;rooms&quot;&gt;
        ///                {{#each rooms}}
        ///                &lt;path id=&quot;{{id}}&quot; fillRule=&quot;evenodd&quot; d=&quot;{{path}}&quot; fill=&quot;#d9d9d9&quot;&gt;
        ///                    &lt;title&gt;{{name}}&lt;/title&gt;
        ///                &lt;/path&gt;
        ///                &lt;g id=&quot;{{id}}-workplaces&quot;&gt;
        ///                    {{#each workplaces}}
        ///                    &lt;path id=&quot;{{id}}&quot; fillRule=&quot;evenodd&quot; fil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level_svg_template {
            get {
                return ResourceManager.GetString("level_svg_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open_panel {
            get {
                object obj = ResourceManager.GetObject("open_panel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap renew {
            get {
                object obj = ResourceManager.GetObject("renew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg version=&quot;1.1&quot; id=&quot;{{id}}&quot; width=&quot;{{width}}&quot; height=&quot;{{height}}&quot;
        ///  viewBox=&quot;0 0 {{width}} {{height}}&quot;&gt;
        ///  &lt;g&gt;
        ///    &lt;g id=&quot;room&quot;&gt;
        ///      &lt;path id=&quot;{{id}}&quot; fillRule=&quot;evenodd&quot; d=&quot;{{path}}&quot; fill=&quot;#d9d9d9&quot;&gt;
        ///        &lt;title&gt;{{name}}&lt;/title&gt;
        ///      &lt;/path&gt;
        ///    &lt;/g&gt;
        ///    &lt;g id=&quot;workplaces&quot;&gt;
        ///      {{#each workplaces}}
        ///      &lt;path id=&quot;{{id}}&quot; fillRule=&quot;evenodd&quot; fill=&quot;white&quot; d=&quot;{{path}}&quot; stroke=&quot;#b5b5b5&quot; stroke-width=&quot;0.2&quot;&gt;
        ///        &lt;title&gt;
        ///          {{name}}
        ///        &lt;/title&gt;
        ///      &lt;/path&gt;
        ///      {{/each}}
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room_svg_template {
            get {
                return ResourceManager.GetString("room-svg-template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;&lt;div class=&quot;&quot;entry&quot;&quot;&gt;
        ///    &lt;h1&gt;{{title}}&lt;/h1&gt;
        ///    &lt;div class=&quot;&quot;body&quot;&quot;&gt;
        ///    {{body}}
        ///    &lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string test_template {
            get {
                return ResourceManager.GetString("test-template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upload {
            get {
                object obj = ResourceManager.GetObject("upload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
